### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by sandeepdevagiri** [DashboardPack/architectui-react-theme-free#11]
When I tried running npm start run I am getting the below error

./src/assets/base.scss (./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-5-1!./node_modules/postcss-loader/src??postcss!./node_modules/resolve-url-loader??ref--6-oneOf-5-3!./node_modules/sass-loader/lib/loader.js??ref--6-oneOf-5-4!./src/assets/base.scss)
Module not found: Can't resolve './components/icons/components/icons/linearicons/Linearicons-Free.eot' in '/Users/sandeepdevagiri/OneDrive/brightsideloans/websites/app_v2/src/assets'

**Comment by vigansokoli** [comment]
Have you tried running npm install first?

**Comment by Imam-N** [comment]
Hi this is perfectly working after npm install. But .Net Core React JS Not Support this One.

Attempted import error: 'UncontrolledPopover' is not exported from 'reactstrap'.

**Comment by shalombar** [comment]
i have the same problem.
I installed the project on one computer and it works.
On another computer I installed with the same package.json this project and i have the same problem of you.
what can be the solution?

**Comment by sublimedatasys** [comment]
@sandeepdevagiri  Please refer #14 issue, Try the solution given there. 

Thank you.
