### ISSUE TITLE
copmile failed

### ISSUE THREAD

**Issue by shalombar** [DashboardPack/architectui-react-theme-free#14]
i did npm install. after that i run the command "npm start".
and i got this error message:

./src/assets/base.scss (./node_modules/css-loader??ref--6-oneOf-5-1!./node_modules/postcss-loader/src??postcss!./node_modules/sass-loader/lib/loader.js??ref--6-oneOf-5-3!./src/assets/base.scss)
Module not found: Can't resolve 'assets/utils/images/logo-inverse.png' in 'C:\Users\shalombar\Desktop\projects\Achieved-Dashboard\src\assets'

**Comment by sunnykushwahasublimedatasys** [comment]
Hello @shalombar , 
Try absolute path instead of relative in "base.css" file replace 
"~assets/utils/images/logo-inverse.png" with "../assets/utils/images/logo-inverse.png"
Also check node-sass version, it should be compatible with your local node environment.

Thank you.

**Comment by SunnyRajaramsinghkushwaha** [comment]
@sunnykushwahasublimedatasys , 
does it work ??

**Comment by bihp** [comment]
Not working for me. Tried the following steps without being able to get away the error message above:

1. Tried to replace relative with absolute paths like stated above. Didn't find anything in base.css but in _header-base.css, _header-dark.css and _userpage.scss and replaced it there --> no effect
2. Did a rebuild of node-sass --> no effect with relative and absolute paths
3. Checked node-sass version. Installed was version 6.14.2. Downgraded to ^4.13.1 like defined in package.json --> no effect with relative and absolute paths

Finally: still have the mentioned error, application not working. Please provide further hints for solution, thanks!

**Comment by 1dveeran** [comment]
Can someone update this thread with a resolution, we bought this theme but we are hampered because of this error.

**Comment by DPTeamMember** [comment]
Hello Everyone,

We have resolved the issue in our latest release.
If you are facing this issue in the ArchitectUI react pro template Please install react-scripts version 3.0.0 the error will go away.

Thank you.
