### ISSUE TITLE
npm run start - compile failure

### ISSUE THREAD

**Issue by dlauck92** [DashboardPack/architectui-react-theme-free#15]
Cannot run npm run start after following all steps in the readme file. Attempted to fix the problem by:

- removing "^"  from "webpack-dev-server": "3.10.1" in the package.json (still failed)
- start.js, test.js & build.js all had 'use strict'; and vs code provided an error stating 'use strict' is unnecessary inside of modules. I removed them and it still failed.

**Comment by dlauck92** [comment]
Ran "npm install webpack-dev-server@2.9.7 --save-dev" in the terminal and it worked. Will this be updated in the future or is it different in the pro version?

**Comment by styk-tv** [comment]
this is the visualisation of PRO support, so get a hint :)

**Comment by dpackdev** [comment]
The free version is just for preview purposes only and we don't maintain it actively. The PRO version is being constantly maintained and updated.

**Comment by dlauck92** [comment]
Thank you for your response. I would update it in case anyone is interested in using your product but wants to try out the free version to see if it's right for them.
