### ISSUE TITLE
How update react-redux to version 7

### ISSUE THREAD

**Issue by felipetmartini1** [DashboardPack/architectui-react-theme-free#19]
Hi,

im trying to merge my app into architectui but my app use react-redux 7 and architectui use version 5, so how i can update architectui to use react-redux 7?

my app use redux function useDispetch so i need version 7, can some one help me?

if i update the package react-redux to version     "react-redux": "~7.1.3", of my app i get no erros in console but just a blank page screem,

Help me plz

**Comment by DPTeamMember** [comment]
Hello @felipetmartini1 

react-redux 7 requires React 16.8.3 or later. Please check your react version. The theme is working with react-redux 7.  Also i suggest you to use "react-redux": "7.2.0".

Thank you.
