### ISSUE TITLE
Not show console.log

### ISSUE THREAD

**Issue by pedroguaillas** [DashboardPack/architectui-react-theme-free#20]
When executing the console.log it does not show in console

**Comment by DPTeamMember** [comment]
Hello @pedroguaillas 

I tried it with a simple example 

`componentDidMount() {
        console.log('I was triggered during componentDidMount')
      }`
just after the class declaration and it worked. you can also try this.
If the console.log is not working in some specific condition, please share some more details.

I am closing this issue for now, you can reopen it if required.

Thank you.
