### ISSUE TITLE
error with "npm install" using VSCode

### ISSUE THREAD

**Issue by shashni** [DashboardPack/architectui-react-theme-free#25]
53650 verbose node v13.6.0
53651 verbose npm  v6.14.5
53652 error code ELIFECYCLE
53653 error errno 1
53654 error fibers@4.0.3 install: `node build.js || nodejs build.js`
53654 error Exit status 1
53655 error Failed at the fibers@4.0.3 install script.
53655 error This is probably not a problem with npm. There is likely additional logging output above.

**Comment by DPTeamMember** [comment]
Hello @shashni 

We have resolved this issue in the latest release.

Thank you.
