### ISSUE TITLE
Failed to compile.

### ISSUE THREAD

**Issue by Lfoposse** [DashboardPack/architectui-react-theme-free#27]
Failed to compile.

./src/assets/base.scss (./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-5-1!./node_modules/postcss-loader/src??postcss!./node_modules/resolve-url-loader??ref--6-oneOf-5-3!./node_modules/sass-loader/dist/cjs.js??ref--6-oneOf-5-4!./src/assets/base.scss)
Module not found: Can't resolve './components/icons/components/icons/linearicons/Linearicons-Free.eot' in '/Users/macbookpro/Projects/Klivar/outils/architectui-react-pro-1.6.0/src/assets'

**Comment by mobius33** [comment]
I am having the same issue. Same error message and same component giving the error.

**Comment by DPTeamMember** [comment]
Hello @Lfoposse @mobius33 

We have resolved this issue in the previous release, please check.

Thank you.
