### ISSUE TITLE
Cannot read property 'entryOption' of undefined

### ISSUE THREAD

**Issue by Sweetyboy** [DashboardPack/architectui-react-theme-free#3]
Hi,

I got this error when I try to launch the project "npm run start"

Could you help me please ?

Prompt error :

> Cannot read property 'entryOption' of undefined
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! architectui-react-theme-free@1.0.0 start: `cross-env NODE_PATH=./src node scripts/start.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the architectui-react-theme-free@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

Log error : 

> 0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\user\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'start' ]
2 info using npm@6.9.0
3 info using node@v10.15.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle architectui-react-theme-free@1.0.0~prestart: architectui-react-theme-free@1.0.0
6 info lifecycle architectui-react-theme-free@1.0.0~start: architectui-react-theme-free@1.0.0
7 verbose lifecycle architectui-react-theme-free@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle architectui-react-theme-free@1.0.0~start: PATH: C:\Users\user\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\DEV\architectui-react\node_modules\.bin;C:\Program Files\nodejs\;C:\Users\user\AppData\Local\Microsoft\WindowsApps;C:\Users\user\AppData\Roaming\npm
9 verbose lifecycle architectui-react-theme-free@1.0.0~start: CWD: D:\DEV\architectui-react
10 silly lifecycle architectui-react-theme-free@1.0.0~start: Args: [ '/d /s /c',
10 silly lifecycle   'cross-env NODE_PATH=./src node scripts/start.js' ]
11 silly lifecycle architectui-react-theme-free@1.0.0~start: Returned: code: 1  signal: null
12 info lifecycle architectui-react-theme-free@1.0.0~start: Failed to exec start script
13 verbose stack Error: architectui-react-theme-free@1.0.0 start: `cross-env NODE_PATH=./src node scripts/start.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\user\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:189:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\user\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:189:13)
13 verbose stack     at maybeClose (internal/child_process.js:970:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid architectui-react-theme-free@1.0.0
15 verbose cwd D:\DEV\architectui-react
16 verbose Windows_NT 10.0.17763
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\user\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "start"
18 verbose node v10.15.3
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 1
22 error architectui-react-theme-free@1.0.0 start: `cross-env NODE_PATH=./src node scripts/start.js`
22 error Exit status 1
23 error Failed at the architectui-react-theme-free@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by fabiojiparana** [comment]
Estou com o mesmo problema!

**Comment by BenjaminB64** [comment]
Update Webpack

**Comment by richardaum** [comment]
This is happening because there's no package-lock file on this repository - which will cause a dependency update. 

**Quick fix:** 
Go to your `package.json` file and remove all version modifiers there - `~` and `^` - this should be enough to run the project.

**Comment by marceloricciardi** [comment]
I could not make it work by removing the version modifiers, nor updating the WebPack and dependencies. Any other tips?

**Comment by goodguy000** [comment]
I think they want us buy this template, not for fee

**Comment by richardaum** [comment]
> I could not make it work by removing the version modifiers, nor updating the WebPack and dependencies. Any other tips?

You shouldn't try to update anything. Just remove the version modifier than run `npm install` and run:

> npm run start

**Comment by ralewis85** [comment]
You just need to remove `^` from `webpack-dev-server` in your `package.json` file.  I have opened a PR to fix this issue.

**Comment by muzeyr** [comment]
Maybe this code will help you,

npm install webpack-dev-server@2.9.7 --save-dev

**Comment by junaid5546** [comment]
Still having problem

**Comment by olabiranj** [comment]
This solves the problem for me, "npm install webpack-dev-server@2.9.7 --save-dev". Thanks @muzeyr

**Comment by Anuradha007** [comment]
> > I could not make it work by removing the version modifiers, nor updating the WebPack and dependencies. Any other tips?
> 
> You shouldn't try to update anything. Just remove the version modifier than run `npm install` and run:
> 
> > npm run start

Thanks ... this helped

**Comment by yahyeShorie** [comment]
Thanks @muzeyr
