### ISSUE TITLE
Error instaling

### ISSUE THREAD

**Issue by mhdali93** [DashboardPack/architectui-react-theme-free#32]
npm install

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: architectui-react-theme-free@1.0.0
npm ERR! Found: webpack@3.5.1
npm ERR! node_modules/webpack
npm ERR!   webpack@"3.5.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer webpack@"^4.0.0" from css-loader@1.0.1
npm ERR! node_modules/css-loader
npm ERR!   dev css-loader@"^1.0.1" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\mmtg0\AppData\Local\npm-cache\eresolve-report.txt for a full report.

Can anyone please update the package.json with the new versions of mode_modules, almost all of them is depricated, and the installation is giving error

**Comment by IhsenBouallegue** [comment]
Didn't want to open a new issue but same problem. I wanted to try the free version before buying the pro one. But when I see over 10 deprecated packages and it fails to even start. I am not really compelled.

**Comment by dpalmeira** [comment]
Same issue to me, it does not work

**Comment by DPTeamMember** [comment]
Hello @dpalmeira @mhdali93 

Issue resolved, Now you can install and run the template without any error.
There are still some deep deprecated dependencies, will update them in the next Major release.

Thank you.
