### ISSUE TITLE
I can't install

### ISSUE THREAD

**Issue by huyentrangle** [DashboardPack/architectui-react-theme-free#37]
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: architectui-react-theme-free@1.1.1
npm ERR! Found: webpack@3.12.0
npm ERR! node_modules/webpack
npm ERR!   webpack@"^3.4.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer webpack@"^4.0.0 || ^5.0.0" from eslint-loader@4.0.2
npm ERR! node_modules/eslint-loader
npm ERR!   eslint-loader@"^4.0.2" from the root project
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\SP-IT\AppData\Local\npm-cache\eresolve-report.txt for a full report.  

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\SP-IT\AppData\Local\npm-cache\_logs\2021-12-07T08_18_03_401Z-debug-0.l

Can you helf me?

**Comment by DPTeamMember** [comment]
Hello @huyentrangle 

The template is compatible with node js version 14.x.x.
please check the same.

Many thanks.

**Comment by Farrenzo** [comment]
Does that mean that anything after 14 will work? I have v16.13 and it is not working with the new node.

**Comment by DPTeamMember** [comment]
Hello @Farrenzo 

Please check the new release, The template is now compatible with node js LTS, and the latest version.

Thank you.
