### ISSUE TITLE
No compila architectui-react-pro-1.7.2

### ISSUE THREAD

**Issue by cristhianfernandezipark** [DashboardPack/architectui-react-theme-free#38]
Compre la plantilla de architectui-react-pro-1.7.2 pero al seguir las indicaciones del index.js de las instrucciones no puedo hacer funcionar y me dan muchos errores (mas de 800).
Alguien sabe como solucionarlo?

Probe instalar una maquina virtual por si era el SO pero nada.
Pruebo con yarn y también me da errores

**Comment by DPTeamMember** [comment]
Hola @cristhianfernandezipark 

Hemos actualizado la plantilla, la nueva versión 2.0.0 ya está disponible en git hub.
Hemos resuelto y actualizado las dependencias.
Por favor, compruebe.

Gracias
