### ISSUE TITLE
error with "npm install"

### ISSUE THREAD

**Issue by williamzv** [DashboardPack/architectui-react-theme-free#4]
MacOS 10.14.5
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.12.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@4.12.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

[2019-07-11T01_12_34_063Z-debug.log](https://github.com/DashboardPack/architectui-react-theme-free/files/3379874/2019-07-11T01_12_34_063Z-debug.log)

**Comment by sublimedatasys** [comment]
@williamzv  , 
It seems that node-sass is not able to find the binary file. try rebuilding the node-sass, Run this command "npm i node-sass rebuild".

Thank you.
