### ISSUE TITLE
problem npm run start

### ISSUE THREAD

**Issue by wil2412** [DashboardPack/architectui-react-theme-free#5]
OS Windows 10:
C:\Users\willi\Desktop\architectui-react-free>npm run start

> architectui-react-theme-free@1.0.0 start C:\Users\willi\Desktop\architectui-react-free
> cross-env NODE_PATH=./src node scripts/start.js

Cannot read property 'entryOption' of undefined
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! architectui-react-theme-free@1.0.0 start: `cross-env NODE_PATH=./src node scripts/start.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the architectui-react-theme-free@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\willi\AppData\Roaming\npm-cache\_logs\
[2019-07-13T17_13_11_496Z-debug.log](https://github.com/DashboardPack/architectui-react-theme-free/files/3389032/2019-07-13T17_13_11_496Z-debug.log)
2019-07-13T17_13_11_496Z-debug.log

**Comment by IgorTishchenko** [comment]
Same on Ubuntu 18.04
![image](https://user-images.githubusercontent.com/47317186/61473219-a5958300-a98e-11e9-96ac-5e836c581409.png)

**Comment by andreisocaciu** [comment]
Same

**Comment by Baterka** [comment]
Same

**Comment by MU-SA** [comment]
delete `^` from webpack-dev-server in `devDependencies` package.json

**Comment by MRHaghighat** [comment]
> delete `^` from webpack-dev-server in `devDependencies` package.json

Not working, the issue still appears on start.

```
Cannot read property 'entryOption' of undefined
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! architectui-react-theme-free@1.0.0 start: `cross-env NODE_PATH=./src node scripts/start.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the architectui-react-theme-free@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by MRHaghighat** [comment]
> Hey ! still nothing?

Hi, Nothing yet and I don't have any idea to fix it.

**Comment by LeonelMV** [comment]
> delete `^` from webpack-dev-server in `devDependencies` package.json

This works perfectly. After you do this change, you must run npm install again. Sorry for my bad english and hope this helps!

**Comment by Emixam23** [comment]
Hey ! Ok I will give it a try, I was just sad since I was hesitating to buy the pro version of it and I can't even run the free version...

**Comment by logicware** [comment]
It runs after deleting ^ from webpack-dev-server in devDependencies package.json. But I get a blank page with warnings in console. 

I am running it on a Linux Mint 19 machine.

See attached screenshot.

![Screenshot from 2019-10-06 16-12-08](https://user-images.githubusercontent.com/2248704/66268170-1e043580-e854-11e9-9c34-3508ffbad6b8.png)

**Comment by arjunp-scc** [comment]
Still having this issue after deleting ^ and re-running install. If anyone can help please let me know.
